package org.dwfa.ace.task;

public enum ProcessAttachmentKeys {
    I_GET_CONCEPT_DATA,
    ACTIVE_CONCEPT, NEW_STATUS, REL_TYPE,
    DEFAULT_CONCEPT_LIST, REL_PARENT, DEFAULT_FILE, WORKING_PROFILE, USERNAME, PASSWORD, ADMIN_USERNAME, ADMIN_PASSWORD,
    HTML_STR, ACTIVE_CONCEPT_UUID, EDIT_PATH_CONCEPT, VIEW_PATH_CONCEPT, SELECTED_ADDRESSES, DUP_UUID_LIST, DUP_UUID_L2,
    DETAIL_HTML_DIR, DETAIL_HTML_FILE, ACTIVE_SVN_ENTRY, DESTINATION_ADR, POT_DUP_UUID, DUP_REVIEW_PROCESS, ASSIGNEE, 
    ALT_ASSIGNEE, PROCESS_NAME, PROCESS_SUBJECT, SIGNPOST_HTML;
    
    public String getAttachmentKey() {
        return "A: " + this.name();
    }
}
