/**
 * Copyright (c) 2009 International Health Terminology Standards Development
 * Organisation
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.dwfa.ace.task.about;

import javax.swing.*;
import java.net.URL;
import java.awt.*;

public class CustomAboutBox extends JDialog {

    private JPanel contentPane;
    private JLabel aboutBoxHtml;

    public CustomAboutBox(JFrame parentFrame, String aboutBoxHtml, String aboutBoxTitle) {

        super(parentFrame);
        setContentPane(contentPane);
        setModal(true);

        layoutAboutBox(aboutBoxTitle, aboutBoxHtml);
    }

    private void layoutAboutBox(String aboutBoxTitle, String aboutBoxHtml) {
        String title = "About the Workflow Bundle";
        if (aboutBoxTitle != null && aboutBoxTitle.length() > 3) {
            title = removeQuotes(aboutBoxTitle);
        }
        this.setTitle(title);
        this.aboutBoxHtml.setText(aboutBoxHtml);
        this.pack();
    }

    public static String removeQuotes(String str) {
        if (str.startsWith("\"")) {
            str = str.substring(1);
        }
        if (str.endsWith("\"")) {
            str = str.substring(0, str.length() - 1);
        }
        return str;
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     * 
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        aboutBoxHtml = new JLabel();
        aboutBoxHtml.setText("");
        contentPane.add(aboutBoxHtml, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
