package org.ihtsdo.rules.test;

import com.termmed.drools_test.Concept;

declare IsRetired
    concept : Concept
end

rule "Add inferred fact"
	salience 50
when
	$c : Concept()
then
	IsRetired retiredFact = new IsRetired();
	retiredFact.setConcept($c);
    insertLogical( retiredFact );
    System.out.println("Inserting inferred fact for " + $c.getName());
end

rule "Find inferred fact"
when
	IsRetired()
then
    System.out.println("Found inferred fact IsRetired");
end

rule "Add inferred fact 2"
	salience 50
when
	$c : Concept( id == 1)
then
	Concept concept2 = new Concept();
	concept2.setId(2);
	concept2.setName("Concept 2");
	concept2.setLast(true);
    insertLogical( concept2 );
    System.out.println("Inserting concept2 as " + $c.getName());
end

rule "Find Concept 2"
when
	Concept( id == 2)
then
    System.out.println("Found Concept 2");
end
