/**
 * Copyright (c) 2009 International Health Terminology Standards Development
 * Organisation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ihtsdo.batch;

import java.util.List;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import org.dwfa.ace.api.I_AmTermComponent;
import org.ihtsdo.batch.BatchActionEvent.BatchActionEventType;
import org.ihtsdo.batch.BatchActionTask.BatchActionTaskType;
import org.ihtsdo.tk.api.ComponentVersionBI;
import org.ihtsdo.tk.api.coordinate.EditCoordinate;
import org.ihtsdo.tk.api.coordinate.ViewCoordinate;
import org.ihtsdo.tk.api.relationship.RelationshipVersionBI;

/**
 *
 * @author marc
 */
public class BatchActionTaskRoleRetireUI extends javax.swing.JPanel implements I_BatchActionTask {

    BatchActionTask task;

    /** Creates new form BatchActionTaskRoleRetireUI */
    public BatchActionTaskRoleRetireUI() {
        initComponents();
        task = new BatchActionTaskRoleRetire();

        // Setup DnD Retire Role Type Panel
        ValueDndNidUI tmp = new ValueDndNidUI("Role Type:");
        GroupLayout layout = (GroupLayout) this.getLayout();
        layout.replace(jPanelDndRetireRoleType, tmp.getPanel());
        jPanelDndRetireRoleType = tmp.getPanel();

        // Setup DnD Retire Role Type Panel
        tmp = new ValueDndNidUI("Role Value:");
        layout.replace(jPanelDndRetireRoleValue, tmp.getPanel());
        jPanelDndRetireRoleValue = tmp.getPanel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDndRetireRoleType = new javax.swing.JPanel();
        jPanelDndRetireRoleValue = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanelDndRetireRoleTypeLayout = new javax.swing.GroupLayout(jPanelDndRetireRoleType);
        jPanelDndRetireRoleType.setLayout(jPanelDndRetireRoleTypeLayout);
        jPanelDndRetireRoleTypeLayout.setHorizontalGroup(
            jPanelDndRetireRoleTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanelDndRetireRoleTypeLayout.setVerticalGroup(
            jPanelDndRetireRoleTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelDndRetireRoleValueLayout = new javax.swing.GroupLayout(jPanelDndRetireRoleValue);
        jPanelDndRetireRoleValue.setLayout(jPanelDndRetireRoleValueLayout);
        jPanelDndRetireRoleValueLayout.setHorizontalGroup(
            jPanelDndRetireRoleValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanelDndRetireRoleValueLayout.setVerticalGroup(
            jPanelDndRetireRoleValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDndRetireRoleType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelDndRetireRoleValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDndRetireRoleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDndRetireRoleValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelDndRetireRoleType;
    private javax.swing.JPanel jPanelDndRetireRoleValue;
    // End of variables declaration//GEN-END:variables

    @Override
    public JPanel getPanel() {
        return this;
    }

    @Override
    public BatchActionTask getTask(EditCoordinate ec, ViewCoordinate vc) throws Exception {
        // SET ROLE TYPE
        I_AmTermComponent termRoleType = ((ValueDndNidUI) jPanelDndRetireRoleType).getTermComponent();
        if (termRoleType != null) {
            ((BatchActionTaskRoleRetire) task).setRoleNid(termRoleType.getNid());
        } else {
            BatchActionEventReporter.add(new BatchActionEvent(null, BatchActionTaskType.ROLE_RETIRE,
                    BatchActionEventType.TASK_INVALID, "role type not set"));
            return null;
        }

        // SET ROLE VALUE
        I_AmTermComponent termRoleValue = ((ValueDndNidUI) jPanelDndRetireRoleValue).getTermComponent();
        if (termRoleValue != null) {
            ((BatchActionTaskRoleRetire) task).setValueNid(termRoleValue.getNid());
        } else {
            BatchActionEventReporter.add(new BatchActionEvent(null, BatchActionTaskType.ROLE_RETIRE,
                    BatchActionEventType.TASK_INVALID, "role value not set"));
            return null;
        }

        return task;
    }

    @Override
    public void updateExisting(List<RelationshipVersionBI> existingParents, List<ComponentVersionBI> existingRefsets, List<RelationshipVersionBI> existingRoles, List<ComponentVersionBI> parentLinkages) {
        // nothing to do
    }
}
