package org.ihtsdo.arena.drools

#list any import classes here.
import java.io.File;
import java.util.Collection;

import org.ihtsdo.tk.api.coordinate.ViewCoordinate;
import org.ihtsdo.tk.drools.facts.ConceptFact;

import org.ihtsdo.arena.context.action.BpActionFactory;

#declare any global variables here

global Collection actions;
global BpActionFactory actionFactory;
global ViewCoordinate vc;

#list any project specific rules for this file here (needs a least one active rule otherwise file should be removed)
rule "sample"
	when
		$c: ConceptFact(getConcept() == null)
	then 
		System.out.println("contextual actions panel rules sample");
end