#created on: Aug 15, 2010
package org.ihtsdo.arena.drools

#list any import classes here.
import java.io.File;
import java.lang.String;
import java.util.Collection;

import org.ihtsdo.tk.api.coordinate.ViewCoordinate;
import org.ihtsdo.tk.drools.facts.ConceptFact;
import org.ihtsdo.tk.drools.facts.Context;
import org.ihtsdo.tk.drools.facts.ConAttrFact;

import org.ihtsdo.arena.context.action.BpActionFactory;
import org.ihtsdo.arena.context.action.CopyDescAction;
import org.ihtsdo.arena.context.action.MoveDescAction;

import org.ihtsdo.tk.spec.DescriptionSpec;

import org.ihtsdo.tk.example.binding.Snomed;
import org.ihtsdo.tk.example.binding.SnomedConstraints;
import org.ihtsdo.tk.example.binding.SnomedRelType;
import org.ihtsdo.tk.example.binding.SnomedRelSpec;
import org.ihtsdo.tk.example.binding.Taxonomies;
import org.ihtsdo.tk.example.binding.WbDescType;
import org.ihtsdo.arena.spec.Refsets; 

#declare any global variables here

global Collection actions;
global BpActionFactory actionFactory;
global ViewCoordinate vc;


rule "add if null concept in host"
	when
		$c: ConceptFact(component == null)
	then 
		actions.add(actionFactory.make(new File("plugins/arena/newconcept.bp"))); 
end

rule "retire or move"
	when
		$c: ConceptFact(component != null); 
	then
		actions.add(actionFactory.make(new File("plugins/retire/retire-concept.bp")));
		actions.add(actionFactory.make(new File("plugins/retire/move-concept.bp")));
		actions.add(actionFactory.make(new File("plugins/arena/newconcept.bp")));
end

rule "abandon concept and restart"
	when
		$c: ConceptFact(component != null, component.conAttrsActive != null,
                    component.conAttrsActive.versions.iterator.next.isUncommitted == true); 
	then
		actions.add(actionFactory.make(new File("plugins/arena/redo-concept.bp")));
end





