package org.ihtsdo.rules.test;

import com.termmed.drools_test.I_Concept;
import com.termmed.drools_test.I_IsLastVersion;
import com.termmed.drools_test.Concept;

rule "Find by interface 1"
when
	I_Concept()
then
    System.out.println("Found by I_Concept");
end

rule "Find by interface 2"
when
	I_IsLastVersion()
then
    System.out.println("Found by I_IsLastVersion");
end

rule "Find by class"
when
	Concept()
then
    System.out.println("Found by Concept");
end

rule "Check if retired"
when
	$c : Concept()
	IsRetired( concept == $c)
then
    System.out.println("Concept is retired!");
end

