#created on: Aug 15, 2010
package org.ihtsdo.arena.drools

#list any import classes here.
import java.io.File;
import java.lang.String;
import java.util.Collection;

import org.ihtsdo.tk.api.coordinate.ViewCoordinate;
import org.ihtsdo.tk.api.conceptattribute.ConceptAttributeVersionBI;
import org.ihtsdo.tk.drools.facts.ConceptFact;
import org.ihtsdo.tk.drools.facts.Context;
import org.ihtsdo.tk.drools.facts.ConAttrFact;

import org.ihtsdo.arena.context.action.BpActionFactory;
import org.ihtsdo.arena.context.action.CopyDescAction;
import org.ihtsdo.arena.context.action.MoveDescAction;

import org.ihtsdo.tk.spec.DescriptionSpec;

import org.ihtsdo.tk.binding.snomed.Snomed;
import org.ihtsdo.tk.binding.snomed.SnomedConstraints;
import org.ihtsdo.tk.binding.snomed.SnomedRelationshipType;
import org.ihtsdo.tk.binding.snomed.SnomedRelationshipSpec;
import org.ihtsdo.tk.binding.snomed.Taxonomies;
import org.ihtsdo.tk.binding.snomed.WbDescType;
import org.ihtsdo.arena.spec.Refsets; 

#declare any global variables here

global Collection actions;
global BpActionFactory actionFactory;
global ViewCoordinate vc;


rule "add if null concept in host"
	when
		$c: ConceptFact(getConcept() == null)
	then 
		File f = new File("plugins/arena/newconcept.bp");
		if(f.exists()){
                    actions.add(actionFactory.make(f));
		}
end

rule "panel has component"
	when
		$c: ConceptFact(getConcept() != null) 
	then
		actions.add(actionFactory.make(new File("plugins/retire/retire-concept.bp")));
		actions.add(actionFactory.make(new File("plugins/retire/move-concept.bp")));
		File f = new File("plugins/arena/newconcept.bp");
		if(f.exists()){
                    actions.add(actionFactory.make(f));
		}
end
