#created on: Aug 15, 2010
package org.ihtsdo.arena.drools

#list any import classes here.
import org.ihtsdo.tk.api.concept.ConceptVersionBI;
import org.ihtsdo.tk.example.binding.Snomed;
import org.ihtsdo.tk.example.binding.SnomedConstraints;
import org.ihtsdo.tk.example.binding.SnomedRelType;
import org.ihtsdo.tk.example.binding.Taxonomies;
import org.ihtsdo.tk.example.binding.WbDescType;


#declare any global variables here


// Parameters x = don't care; e = equals, k = kind of, r = regex

rule "isKindOf refset concept"
	
	when
		$c : ConceptVersionBI(
				this isKindOf Taxonomies.REFSET_AUX);
	then 
   		System.out.println("isKindOf refset concept found: \n" + $c.toString());
		
end

rule "not satisfies rel constraint"
	
	when
		$c : ConceptVersionBI(this not satisfiesConstraint[x,e,k] SnomedConstraints.FINDING_SITE_OUT);
	then 
   		System.out.println("concept failing FINDING_SITE_OUT constraint found: \n" + $c.toString());
		
end

rule "not satisfies desc constraint"
	
	when
		$c : ConceptVersionBI(this not satisfiesConstraint[x,e,r] SnomedConstraints.FS_SEMANTIC_TAG);
	then 
   		System.out.println("concept failing FS_SEMANTIC_TAG constraint found: \n" + $c.toString());
		
end


rule "isKindOf refset concept and not satisfies rel constraint"
	
	when
		$c : ConceptVersionBI(this isKindOf Taxonomies.REFSET_AUX,
							  this not satisfiesConstraint[x,e,k] SnomedConstraints.FINDING_SITE_OUT);
	then 
   		System.out.println("isKindOf refset concept failing FINDING_SITE_OUT constraint found: \n" + $c.toString());
		
end


rule "isKindOf workbench auxiliary concept"
	
	when
		$c : ConceptVersionBI(this isKindOf Taxonomies.WB_AUX);
	then 
   		System.out.println("isKindOf workbench auxiliary concept found: \n" + $c.toString());
		
end

rule "isKindOf queue type concept"
	
	when
		$c : ConceptVersionBI(this isKindOf Taxonomies.QUEUE_TYPE);
	then 
   		System.out.println("isKindOf queue type concept found: \n" + $c.toString());
		
end

rule "isKindOf SNOMED concept"
	
	when
		$c : ConceptVersionBI(this isKindOf Taxonomies.SNOMED);
	then 
   		System.out.println("isKindOf SNOMED concept found: \n" + $c.toString());
		
end
